version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.9
        environment:
          DB_HOST: localhost
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432

      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    working_directory: ~/app

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: migrate and collectstatic
          command: |
            . venv/bin/activate
            cd circle_dj_pg_demo
            python manage.py collectstatic --no-input
            python manage.py migrate --no-input
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd app
            python manage.py test